import type { DeckData } from "./types";

export const SAMPLE_DECK: DeckData = {
  theme: "trygc",
  font: "editorial-premium",
  meta: {
    brand: "Grand Community",
    client: "Starbucks",
    date: "April 20, 2026",
    market: "KSA",
    footer: "Speak · Connect · Impact",
  },
  slideOrder: [
    "cover",
    "executive",
    "interaction",
    "leader",
    "engagement",
    "platforms",
    "geography",
    "cities",
    "content",
    "commercial",
    "recommendations",
    "closing",
  ],
  slides: {
    cover: {
      visible: true,
      layout: "poster",
      kicker: "Starbucks Partnership",
      title: "National Creator Engine Across KSA",
      lead: "A premium executive view of campaign scale, creator footprint, measured views, engagement quality, and next moves.",
      kpis: ["campaigns", "records", "footprintShort"],
    },
    executive: {
      visible: true,
      layout: "matrix",
      kicker: "Executive Summary",
      title: "Scale, visibility, and measurable performance",
      lead: "The campaign built a large influencer-record base with a strong potential follower footprint and tracked view delivery.",
      kpis: ["campaigns", "records", "footprintShort", "viewsShort"],
      chart: "monthly",
    },
    interaction: {
      visible: true,
      layout: "dashboard",
      kicker: "Performance Quality",
      title: "Interactions converted attention into audience action",
      lead: "Engagement is separated from reach to make the performance story clean and procurement-ready.",
      kpis: ["interactionsShort", "interactionRate", "viewsPerRecord", "uniqueHandles"],
      chart: "interactionMix",
    },
    leader: {
      visible: true,
      layout: "spotlight",
      kicker: "Platform Leadership",
      title: "The leading segment generated the majority of views",
      lead: "The strongest segment delivered most of the total view volume and outperformed the TikTok interaction-rate benchmark.",
      kpis: ["leaderShare", "leaderIR", "tiktokIR"],
    },
    engagement: {
      visible: true,
      layout: "dashboard",
      kicker: "Engagement Breakdown",
      title: "Likes, comments, saves, and shares each tell a different story",
      lead: "The interaction mix shows both passive approval and high-intent actions such as saves and shares.",
      kpis: ["likes", "comments", "saves", "shares"],
      chart: "interactionMix",
    },
    platforms: {
      visible: true,
      layout: "chartFull",
      kicker: "Channel Performance",
      title: "Platform mix shows where attention scaled fastest",
      lead: "Views and interaction rates are shown by platform layer to identify the strongest execution lanes.",
      kpis: ["segmentViews", "segmentViewsPerInfluencer", "leaderIR"],
      chart: "platforms",
    },
    geography: {
      visible: true,
      layout: "map",
      kicker: "Geography Footprint",
      title: "National coverage with local relevance",
      lead: "The campaign footprint extends across branches, cities, and regions, keeping the brand present beyond one hero market.",
      kpis: ["branches", "cities", "regions", "activeMonths"],
    },
    cities: {
      visible: true,
      layout: "ranking",
      kicker: "Top Cities",
      title: "Riyadh and Jeddah carry the highest activation weight",
      lead: "City ranking is displayed independently without repeating the headline total figures.",
      kpis: ["branches", "cities"],
      chart: "cities",
    },
    content: {
      visible: true,
      layout: "mixed",
      kicker: "Content Engine",
      title: "Content mix balances stories, posts, reels, and highlights",
      lead: "The creative mix shows where format investment is concentrated and where discovery upside exists.",
      kpis: ["contentRecords", "activeMonths"],
      chart: "contentMix",
    },
    commercial: {
      visible: true,
      layout: "finance",
      kicker: "Commercial Efficiency",
      title: "A flat-rate creator model protects budget at scale",
      lead: "The model converts creator execution into an efficiency story, not only a marketing story.",
      kpis: ["costProtected", "flatRate"],
      chart: "monthly",
    },
    recommendations: {
      visible: true,
      layout: "ems",
      kicker: "EMS Recommendations",
      title: "Execution Management System for the next wave",
      lead: "A sharper operating model turns campaign output into repeatable monthly governance and proof.",
    },
    closing: {
      visible: true,
      layout: "closing",
      kicker: "The Achievement",
      title: "We built reach. We protected budget. We kept Starbucks top of mind.",
      lead: "A clean, measurable creator engine with a scalable operating model across KSA.",
      kpis: ["records", "viewsShort", "interactionsShort", "branches"],
    },
  },
  metrics: {
    campaigns: { label: "Campaigns", value: "22", note: "Campaign count across the program." },
    records: { label: "Influencer Records", value: "10,483", note: "Influencer-campaign records." },
    footprintShort: { label: "Potential Follower Footprint", value: "795.3M", note: "Rounded executive view." },
    viewsShort: { label: "Total Views", value: "24.64M", note: "Rounded executive view." },
    interactionsShort: { label: "Total Interactions", value: "1.16M", note: "Rounded engagement total." },
    interactionRate: { label: "Overall Interaction Rate", value: "4.7%", note: "Total interactions divided by views." },
    viewsPerRecord: { label: "Views / Influencer Record", value: "2,350", note: "Average views per influencer-campaign record." },
    uniqueHandles: { label: "Unique Influencer Handles", value: "3,905", note: "Deduplicated creator handles." },
    leaderShare: { label: "Share of Total Views", value: "87.7%", note: "Generated by the leading segment." },
    leaderIR: { label: "Leading Segment IR", value: "6.0%", note: "Interaction rate for the leading segment." },
    tiktokIR: { label: "TikTok IR Benchmark", value: "4.5%", note: "Benchmark interaction rate." },
    segmentViews: { label: "Segment Views", value: "6.58M", note: "Views generated by the highlighted segment." },
    segmentViewsPerInfluencer: { label: "Views / Influencer", value: "10,238", note: "Average segment views per influencer." },
    likes: { label: "Total Likes", value: "874,833", note: "Approval and positive response signal." },
    comments: { label: "Total Comments", value: "65,186", note: "Conversation signal." },
    saves: { label: "Total Saves", value: "142,927", note: "High-intent retention signal." },
    shares: { label: "Total Shares", value: "75,576", note: "Advocacy and amplification signal." },
    branches: { label: "Branches Covered", value: "104", note: "Unique Starbucks branches." },
    cities: { label: "Cities Covered", value: "53", note: "City footprint." },
    regions: { label: "Regions / States", value: "13", note: "KSA region coverage." },
    activeMonths: { label: "Active Months", value: "8", note: "Jul 2025 to Feb 2026." },
    contentRecords: { label: "Content Records", value: "10,123", note: "Published output records." },
    costProtected: { label: "Budget Protected", value: "98.85M SAR", note: "Versus low market benchmark." },
    flatRate: { label: "Flat Rate Model", value: "4.12M SAR", note: "Estimated GC effective model cost." },
  },
  charts: {
    interactionMix: [
      { name: "Likes", value: 874833 },
      { name: "Comments", value: 65186 },
      { name: "Saves", value: 142927 },
      { name: "Shares", value: 75576 },
    ],
    platforms: [
      { name: "Leading Segment", views: 21600000, rate: 6 },
      { name: "TikTok", views: 6580000, rate: 4.5 },
      { name: "Other Channels", views: 3520000, rate: 3.2 },
    ],
    cities: [
      { name: "Riyadh", value: 38 },
      { name: "Jeddah", value: 24 },
      { name: "Eastern Province", value: 14 },
      { name: "Makkah", value: 9 },
      { name: "Madinah", value: 7 },
      { name: "Other Cities", value: 8 },
    ],
    contentMix: [
      { name: "Stories", value: 4200 },
      { name: "Posts", value: 2800 },
      { name: "Reels", value: 2300 },
      { name: "Highlights", value: 823 },
    ],
    monthly: [
      { name: "Jul 2025", value: 1.8 },
      { name: "Aug 2025", value: 2.4 },
      { name: "Sep 2025", value: 2.9 },
      { name: "Oct 2025", value: 3.4 },
      { name: "Nov 2025", value: 3.6 },
      { name: "Dec 2025", value: 4.1 },
      { name: "Jan 2026", value: 3.5 },
      { name: "Feb 2026", value: 2.94 },
    ],
  },
  recommendations: [
    { title: "Always-on creator calendar", priority: "High", desc: "Lock a monthly branch and city-cluster calendar before execution starts.", owner: "GC Ops", cadence: "Monthly", nextStep: "Publish Q3 calendar by next Mon." },
    { title: "Increase short-form video share", priority: "High", desc: "Shift more output toward reels/video to improve discovery and recall.", owner: "Creative Lead", cadence: "Weekly", nextStep: "Adjust creator briefs." },
    { title: "Standardize leadership dashboard", priority: "Medium", desc: "Track month, channel, city, branch, views, interactions, and proof links.", owner: "Analytics", cadence: "Monthly", nextStep: "Roll out v1 dashboard." },
    { title: "Prioritize top locations", priority: "Medium", desc: "Repeat investment in the highest-performing cities and branches.", owner: "Account", cadence: "Quarterly", nextStep: "Approve city tier list." },
    { title: "Branch-level proof packs", priority: "Medium", desc: "Package monthly proof for store leaders and regional stakeholders.", owner: "Client Services", cadence: "Monthly", nextStep: "Template + first 5 stores." },
    { title: "Continue flat-rate network model", priority: "Ongoing", desc: "Keep the model as a procurement and operations efficiency advantage.", owner: "Procurement", cadence: "Ongoing", nextStep: "Renew agreements." },
  ],
};
